#### 3. Write a program to construct a Bayesian network considering medical data. Use this model to demonstrate the diagnosis of heart patients using the standard Heart Disease Data Set (You can use Java/Python ML library classes/API.)

In [2]:
import pandas as pd
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

In [3]:
data = pd.read_csv('heart.csv')
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
# keeping only imp features
new_df = data[['cp', 'thalach', 'exang', 'oldpeak', 'ca', 'thal', 'target']]
new_df.head()

   cp  thalach  exang  oldpeak  ca  thal  target
0   0      168      0      1.0   2     3       0
1   0      155      1      3.1   0     3       0
2   0      125      1      2.6   0     3       0
3   0      161      0      0.0   1     3       0
4   0      106      0      1.9   3     2       0

In [5]:
# Define the structure of your Bayesian network
model = BayesianNetwork([
    ('cp', 'target'),
    ('thalach', 'target'),
    ('exang', 'target'),
    ('oldpeak', 'target'),
    ('ca', 'target'),
    ('thal', 'target')
])

In [6]:
# Learn the parameters of the network from the data
model.fit(new_df, estimator=MaximumLikelihoodEstimator)

In [9]:
# Perform inference
inference = VariableElimination(model)

In [10]:
# You can now query the network for the probability of heart disease given some evidence
# Example evidence (you can replace this with actual patient data)
evidence = {
    'cp': data.at[0, 'cp'],
    'thalach': data.at[0, 'thalach'],
    'exang': data.at[0, 'exang'],
    'oldpeak': data.at[0, 'oldpeak'],
    'ca': data.at[0, 'ca'],
    'thal': data.at[0, 'thal']
}

In [11]:
# Query the network
result = inference.query(variables=['target'], evidence=evidence)
print(result)

+-----------+---------------+
| target    |   phi(target) |
+===========+===============+
| target(0) |        1.0000 |
+-----------+---------------+
| target(1) |        0.0000 |
+-----------+---------------+